"""Runtime-neutral simulation snapshot primitives."""

from linkerbot_sim.snapshots.compatibility import (
    JointMapping,
    ObjectCompatibilityMapping,
    ObjectTargetDescriptor,
    RobotCompatibilityMapping,
    RobotTargetDescriptor,
    SnapshotCompatibilityError,
    SnapshotCompatibilityResult,
    SnapshotTargetDescriptor,
    check_snapshot_compatibility,
    require_snapshot_compatibility,
)
from linkerbot_sim.snapshots.adapters import (
    clone_tiled_env_state,
    dual_target_descriptor,
    get_dual_robot_snapshot,
    get_single_robot_snapshot,
    get_snapshot,
    get_tiled_snapshot,
    set_dual_robot_snapshot,
    set_single_robot_snapshot,
    set_snapshot,
    set_tiled_snapshot,
    single_target_descriptor,
    tiled_target_descriptor,
)
from linkerbot_sim.snapshots.schema import (
    SCHEMA_VERSION,
    ObjectSnapshot,
    RobotSnapshot,
    SimulationSnapshot,
    SnapshotMetadata,
    SnapshotRestoreResult,
)

__all__ = [
    "SCHEMA_VERSION",
    "JointMapping",
    "ObjectCompatibilityMapping",
    "ObjectSnapshot",
    "ObjectTargetDescriptor",
    "RobotCompatibilityMapping",
    "RobotSnapshot",
    "RobotTargetDescriptor",
    "SimulationSnapshot",
    "SnapshotCompatibilityError",
    "SnapshotCompatibilityResult",
    "SnapshotMetadata",
    "SnapshotRestoreResult",
    "SnapshotTargetDescriptor",
    "check_snapshot_compatibility",
    "clone_tiled_env_state",
    "dual_target_descriptor",
    "get_dual_robot_snapshot",
    "get_single_robot_snapshot",
    "get_snapshot",
    "get_tiled_snapshot",
    "require_snapshot_compatibility",
    "set_dual_robot_snapshot",
    "set_single_robot_snapshot",
    "set_snapshot",
    "set_tiled_snapshot",
    "single_target_descriptor",
    "tiled_target_descriptor",
]
